package gogreenserver.controllers;

import gogreenserver.entity.FoodEmission;
import gogreenserver.services.FoodEmissionService;

import org.apache.logging.log4j.Logger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.core.Authentication;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

//import org.springframework.web.bind.annotation.*;

/**
 * controller of the endpoint /foodemission through which client can retrive how
 * mucn CO2 is generated by consuming a particular kind of food.
 */
@RestController
@RequestMapping("/api")
public class FoodEmissionController {

    private FoodEmissionService service;
    private final Logger logger;

    @Autowired
    public FoodEmissionController(FoodEmissionService foodService, Logger logger) {
        this.service = foodService;
        this.logger = logger;
    }

    /**
     * Returns the food emission object.
     *
     * @param foodName the name of the food that you ate.
     * @return a responseEntity.
     */
    @PostMapping("/foodEmission")
    public ResponseEntity<FoodEmission> addFoodEmission(@RequestBody String foodName,
            Authentication auth) {
        logger.debug("POST /foodEmission/ with body \"" + foodName + "\" accessed by: "
                + auth.getName());
        FoodEmission foodEmissionResponse = service.findById(foodName).orElse(null);
        return new ResponseEntity<FoodEmission>(foodEmissionResponse, HttpStatus.OK);
    }

}
